cpr_generic_e/sensors/lidar3d_1:
  hesai_driver:
    ros__parameters:
      config_path: '/path/to/hesai/config/file1.yaml'
      frame_id: 'lidar3d_1_hesai'
      device_ip: '192.168.131.26'
      port: 0
