cpr_generic_e/sensors/lidar3d_0:
  hesai_driver:
    ros__parameters:
      config_path: '/path/to/hesai/config/file0.yaml'
      frame_id: 'lidar3d_0_hesai'
      device_ip: '192.168.131.25'
      port: 0
